spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true

    flyway:
      enabled: true
      locations: classpath:db/migration
